[package]
name = "minsql"
version = "0.1.0"
authors = ["Daniel Valdivia <daniel@minio.io>"]
edition = "2018"

[dependencies]

regex = "1"
futures = "0.1.27"
hyper = "0.12.28"
log = "0.4.6"
pretty_env_logger = "0.3.0"
serde_json = "1.0"
toml = "0.4.2"
serde = "1.0.91"
serde_derive = "1.0.91"
rusoto_core = "0.38.0"
rusoto_s3 = "0.38.0"
rusoto_credential = "0.17.0"
xml-rs = "0.8.0"